<a href="https://colab.research.google.com/github/Aishwarya149/ads1/blob/main/TensorflowDatacamp-constant%26variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
d0 = tf.ones((0,))

In [3]:
d1 = tf.ones((2,))

In [5]:
d2 = tf.ones((2,2))
d3 = tf.ones((2,2,2))
print(d0,d1,d2)
print(d3.numpy())

tf.Tensor([], shape=(0,), dtype=float32) tf.Tensor([1. 1.], shape=(2,), dtype=float32) tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [7]:
from tensorflow import constant
a = constant(3, shape=[2,3])
b = constant([1,2,3,4], shape=[2,2])
print(a,b)

tf.Tensor(
[[3 3 3]
 [3 3 3]], shape=(2, 3), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [8]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [10]:
tf.zeros([2,2])
#tf.zeros_like(input_tensor)
#tf.ones_like(input_tensor)
tf.fill([3,3],7)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int32)>